databases:
  - name: skechwime
    plan: free
    databaseName: skechwimedb
    user: skechwime

services:
  - type: web
    plan: free
    name: skechwime
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn skechwime.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: skechwimedb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
