# Generated by Django 3.2.25 on 2024-04-22 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('canvas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='canvas',
            field=models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='canvas.canvas'),
        ),
        migrations.AddField(
            model_name='lobby',
            name='creator',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
