# Generated by Django 3.2.25 on 2024-04-22 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0002_auto_20240422_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobby',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
