# Generated by Django 3.2.25 on 2024-04-22 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0003_alter_lobby_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvas',
            name='lobby',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uniquecanvas', to='canvas.lobby'),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='canvas',
            field=models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uniquelobby', to='canvas.canvas'),
        ),
    ]
